"""Aupdate

Revision ID: 28202085da30
Revises: 4cac47187cf6
Create Date: 2025-08-03 01:19:04.960483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28202085da30'
down_revision: Union[str, Sequence[str], None] = '4cac47187cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
